# Generated by Django 4.2.3 on 2023-08-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0002_imagem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagem",
            options={"verbose_name_plural": "Imagens"},
        ),
        migrations.AddField(
            model_name="produto",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
        ),
    ]
